export const extractCurrencies = (results: any[]) => {
  return {
    btc: results[0],
    // bch
    bch: results[1],
    bchBtc: results[2],
    // eth
    eth: results[3],
    ethBtc: results[4],
    ethBch: results[5],
    // cet
    cet: results[6],
    cetBtc: results[7],
    cetBch: results[8],
    cetEth: results[9],
    // ada
    ada: results[10],
    adaBtc: results[11],
    adaBch: results[12],
    // doge
    doge: results[13],
    dogeBtc: results[14],
    dogeBch: results[15],
    // ltc
    ltc: results[16],
    ltcBtc: results[17],
    ltcBch: results[18],
    // vet
    vet: results[19],
    vetBtc: results[20],
    vetBch: results[21],
    vetEth: results[22],
    // bnb
    bnb: results[23],
    bnbBtc: results[24],
    bnbBch: results[25],
    // xrp
    xrp: results[26],
    xrpBtc: results[27],
    xrpBch: results[28],
    // etc
    etc: results[29],
    etcBtc: results[30],
    etcBch: results[31],
    // dot
    dot: results[32],
    dotBtc: results[33],
    dotBch: results[34],
    // sol
    sol: results[35],
    solBtc: results[36],
    solBch: results[37],
    // trx
    trx: results[38],
    trxBtc: results[39],
    trxBch: results[40],
    trxEth: results[41],
    // eos
    eos: results[42],
    eosBtc: results[43],
    eosBch: results[44],
    eosEth: results[45],
    // xmr
    xmr: results[46],
    xmrBtc: results[47],
    xmrBch: [48],
  };
};
